"""empty message

Revision ID: f4b66120107a
Revises: 4e10ec8dc24f
Create Date: 2020-05-25 18:39:22.655940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b66120107a'
down_revision = '4e10ec8dc24f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('question', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'created')
    op.drop_column('answer', 'created')
    # ### end Alembic commands ###
